// Instale @electric-sql/pglite em uma pasta temporária e passe a pasta como argumento.
const {PGlite}=require(require('node:path').join(process.argv[2],'node_modules/@electric-sql/pglite'));
const fs=require('node:fs');
const assert=require('node:assert/strict');
(async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to authenticated,anon;
 grant execute on function auth.uid() to authenticated,anon;`);
 await db.exec(fs.readFileSync('supabase-saas.sql','utf8'));
 await db.exec(fs.readFileSync('supabase-personalizacao.sql','utf8'));
 // Contrato mínimo do Storage para testar as políticas em PostgreSQL local.
 await db.exec(`create schema storage; grant usage on schema storage to anon,authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text not null);
 create function storage.foldername(name text) returns text[] language sql immutable as $$select (string_to_array(name,'/'))[1:1]$$;
 alter table storage.objects enable row level security;
 grant select,insert,delete on storage.objects to anon,authenticated;`);
 await db.exec(fs.readFileSync('supabase-fotos-profissionais.sql','utf8'));
 await db.exec(fs.readFileSync('supabase-fotos-profissionais.sql','utf8'));
 const a='10000000-0000-4000-8000-000000000001', b='10000000-0000-4000-8000-000000000002';
 await db.query('insert into auth.users values($1),($2)',[a,b]);
 async function conta(user){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec('set role authenticated');}
 await conta(a);
 const lojaA=(await db.query("select public.saas_criar_barbearia('Loja A','loja-a','5579999999999') id")).rows[0].id;
 const servicoA=(await db.query("insert into public.saas_servicos(barbearia_id,nome,preco,categoria) values($1,'Corte',30,'individual') returning id",[lojaA])).rows[0].id;
 await conta(b);
 const lojaB=(await db.query("select public.saas_criar_barbearia('Loja B','loja-b','5579999999998') id")).rows[0].id;
 const profissionalA=(await db.query('select id from public.saas_profissionais where barbearia_id=$1',[lojaA])).rows[0].id;
 const profissionalB=(await db.query('select id from public.saas_profissionais where barbearia_id=$1',[lojaB])).rows[0].id;
 const fotoA=lojaA+'/20000000-0000-4000-8000-000000000001.jpg',fotoB=lojaB+'/20000000-0000-4000-8000-000000000002.png';
 assert.equal((await db.query('update public.saas_profissionais set foto=$1 where id=$2 returning id',[fotoA,profissionalA])).rows.length,0);
 await assert.rejects(()=>db.query('update public.saas_profissionais set foto=$1 where id=$2',[fotoA,profissionalB]));
 await assert.rejects(()=>db.query("update public.saas_profissionais set foto='javascript:alert(1)' where id=$1",[profissionalB]));
 await db.query('update public.saas_profissionais set foto=$1 where id=$2',[fotoB,profissionalB]);
 await assert.rejects(()=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['fotos-profissionais',fotoA]));
 await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['fotos-profissionais',fotoB]);
 await assert.rejects(()=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['fotos-profissionais',lojaB+'/arquivo.svg']));
 await conta(a);
 assert.equal((await db.query('select * from storage.objects where name=$1',[fotoB])).rows.length,0);
 assert.equal((await db.query('delete from storage.objects where name=$1 returning id',[fotoB])).rows.length,0);
 await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['fotos-profissionais',fotoA]);
 assert.equal((await db.query('delete from storage.objects where name=$1 returning id',[fotoA])).rows.length,1);
 await conta(b);
 const paleta=(await db.query("update public.saas_barbearias set cor_principal='#14532d',cor_destaque='#eab308',cor_fundo='#111111' where id=$1 returning cor_principal,cor_destaque,cor_fundo",[lojaB])).rows[0];
 assert.deepEqual(paleta,{cor_principal:'#14532d',cor_destaque:'#eab308',cor_fundo:'#111111'});
 assert.equal((await db.query("update public.saas_barbearias set cor_principal='#ffffff' where id=$1 returning id",[lojaA])).rows.length,0);
 await assert.rejects(()=>db.query("update public.saas_barbearias set cor_fundo='url(https://exemplo.invalid)' where id=$1",[lojaB]));
 const servicoB=(await db.query("insert into public.saas_servicos(barbearia_id,nome,preco,categoria) values($1,'Corte',40,'individual') returning id",[lojaB])).rows[0].id;
 assert.equal((await db.query('select * from public.saas_membros')).rows.length,1);
 assert.equal((await db.query('select * from public.saas_expediente where barbearia_id=$1',[lojaA])).rows.length,0);
 assert.equal((await db.query("update public.saas_servicos set preco=1 where id=$1 returning id",[servicoA])).rows.length,0);
 await assert.rejects(()=>db.query("insert into public.saas_bloqueios(barbearia_id,data) values($1,current_date)",[lojaA]));
 await assert.rejects(()=>db.query("update public.saas_servicos set barbearia_id=$1 where id=$2",[lojaA,servicoB]));
 await assert.rejects(()=>db.query("insert into public.saas_membros(user_id,barbearia_id) values($1,$2)",[a,lojaB]));
 await assert.rejects(()=>db.query("select public.saas_salvar_expediente($1,'[]')",[lojaA]));
 await assert.rejects(()=>db.query("select public.saas_criar_barbearia('Outra','outra','5579999999999')"));
 await db.exec('reset role');
 await db.query('update public.saas_expediente set aberto=true');
 const dia=(await db.query("select ((now() at time zone 'America/Sao_Paulo')::date+1)::text dia")).rows[0].dia;
 await db.exec('set role anon');
 assert.equal((await db.query('select foto from public.saas_profissionais where id=$1',[profissionalB])).rows[0].foto,fotoB);
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await assert.rejects(()=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['fotos-profissionais',fotoB]));
 assert.equal((await db.query('delete from storage.objects where name=$1 returning id',[fotoB])).rows.length,0);
 assert.equal((await db.query('select cor_principal from public.saas_barbearias where id=$1',[lojaB])).rows[0].cor_principal,'#14532d');
 assert.equal((await db.query('select cor_principal from public.saas_barbearias where id=$1',[lojaA])).rows[0].cor_principal,'#262878');
 await assert.rejects(()=>db.query("update public.saas_barbearias set cor_principal='#000000' where id=$1",[lojaB]));
 const horarios=(await db.query('select * from public.saas_horarios_livres($1,$2,\'sem-preferencia\')',[lojaA,dia])).rows;
 assert.ok(horarios.length>0);
 const hora=horarios[0].horario;
 const reservaA=(await db.query("select public.saas_reservar($1,$2,$3,'sem-preferencia',$4,'Cliente A','79999999999') r",[lojaA,dia,hora,servicoA])).rows[0].r;
 await assert.rejects(()=>db.query("select public.saas_reservar($1,$2,$3,'sem-preferencia',$4,'Cliente B','79999999999')",[lojaA,dia,hora,servicoA]));
 await assert.rejects(()=>db.query("select public.saas_reservar($1,$2,$3,'sem-preferencia',$4,'Cliente','79999999999')",[lojaA,dia,horarios[1].horario,servicoB]));
 await db.query("select public.saas_reservar($1,$2,$3,'sem-preferencia',$4,'Cliente B','79999999999')",[lojaB,dia,hora,servicoB]);
 await assert.rejects(()=>db.query('select * from public.saas_reservas'));
 await assert.rejects(()=>db.query("select public.saas_criar_barbearia('X','xxx','5579999999999')"));
 await conta(b);
 const reservasB=(await db.query('select * from public.saas_reservas')).rows;
 assert.equal(reservasB.length,1);assert.equal(reservasB[0].barbearia_id,lojaB);
 assert.equal((await db.query("update public.saas_reservas set status='cancelado' where id=$1 returning id",[reservaA.id])).rows.length,0);
 await db.query('update public.saas_controle_agenda set pausado=true where barbearia_id=$1',[lojaB]);
 await db.exec('reset role;set role anon');
 assert.equal((await db.query("select * from public.saas_horarios_livres($1,$2,'sem-preferencia')",[lojaB,dia])).rows.length,0);
 console.log('OK: instalação SQL, cadastro de duas lojas, RLS, isolamento, fotos e Storage, reserva, conflito, serviço de outra loja, privacidade e pausa.');
 await db.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
